import './globals.css';

import { Providers } from '@/redux/provider';

// export const metadata: Metadata = {
//   title: 'Notes Generator',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
